
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - database_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
    networks:
      - database_network

  ravendb:
    image: ravendb/ravendb:latest
    container_name: ravendb
    environment:
      RAVEN_Setup_Mode: None
      RAVEN_License_Eula_Accepted: "true"
    ports:
      - "8080:8080"
      - "38888:38888"
    networks:
      - database_network

networks:
  database_network:
    driver: bridge
